nicknames = {'category':'category',
'Day':'Day',
'session':'session',
'Order':'Order',
'Timestamp':'Timestamp',
'Email Address':'Email Address',
'First author: Surname':'surname1',
'First author: Given name(s)':'given-names1',
'First author: Institutional affiliation':'aff1',
'Abstract Title (120 character limit)':'article-title',
'Abstract Text (1500 character limit)':'abstract',
'Funding Acknowledgements':'fn-group',
'Presentation Preference':'Presentation Preference',
'Is the presenting author eligible for the Young Investigator Award?':'Is the presenting author eligible for the Young Investigator Award?',
'Author 2: Surname':'surname2',
'Author 2: Given name(s)':'given-names2',
'Author 2: Institutional affiliation':'aff2',
'Author 3: Surname':'surname3',
'Author 3: Given name(s)':'given-names3',
'Author 3: Institutional affiliation':'aff3',
'Author 4: Surname':'surname4',
'Author 4: Given name(s)':'given-names4',
'Author 4: Institutional affiliation':'aff4',
'Author 5: Surname':'surname5',
'Author 5: Given name(s)':'given-names5',
'Author 5: Institutional affiliation':'aff5',
'Do you have additional authors to add?':'Do you have additional authors to add?',
'Author 6: Surname':'surname6',
'Author 6: Given name(s)':'given-names6',
'Author 6: Institutional affiliation':'aff6',
'Author 7: Surname':'surname7',
'Author 7: Given name(s)':'given-names7',
'Author 7: Institutional affiliation':'aff7',
'Author 8: Surname':'surname8',
'Author 8: Given name(s)':'given-names8',
'Author 8: Institutional affiliation':'aff8',
'Author 9: Surname':'surname9',
'Author 9: Given name(s)':'given-names9',
'Author 9: Institutional affiliation':'aff9',
'Author 10: Surname':'surname10',
'Author 10: Given name(s)':'given-names10',
'Author 10: Institutional affiliation':'aff10',
'Do you have additional authors to add?.1':'Do you have additional authors to add?.1',
'Author 11: Surname':'surname11',
'Author 11: Given name(s)':'given-names11',
'Author 11: Institutional affiliation':'aff11',
'Author 12: Surname':'surname12',
'Author 12: Given name(s)':'given-names12',
'Author 12: Institutional affiliation':'aff12',
'Author 13: Surname':'surname13',
'Author 13: Given name(s)':'given-names13',
'Author 13: Institutional affiliation':'aff13',
'Author 14: Surname':'surname14',
'Author 14: Given name(s)':'given-names14',
'Author 14: Institutional affiliation':'aff14',
'Author 15: Surname':'surname15',
'Author 15: Given name(s)':'given-names15',
'Author 15: Institutional affiliation':'aff15'}

